apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - model-cache-pvc.yaml
  - inference-service-qwen35-122b.yaml
  - service-qwen35-122b-public.yaml
  - inference-service-minimax-m25.yaml
  - service-minimax-m25-public.yaml
  - inference-service-qwen3-coder.yaml
  - service-qwen3-coder-public.yaml
