apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen35-122b-model-cache
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 160Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minimax-m25-model-cache
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-coder-model-cache
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-coder-fp8-model-cache
  namespace: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: openebs-hostpath
