apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-model-sa
  namespace: llm
annotations:
  serving.kserve.io/s3-endpoint: REPLACE_S3_ENDPOINT
  serving.kserve.io/s3-usehttps: "1"
  serving.kserve.io/s3-region: REPLACE_S3_REGION
