apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-model-sa
  namespace: llm
  annotations:
    serving.kserve.io/storageSecretName: llm-s3-credentials
    serving.kserve.io/s3-endpoint: s3.regru.cloud
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: us-east-1
