apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-20b-public
  namespace: llm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: isvc.gpt-oss-20b-predictor
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32090
