apiVersion: v1
kind: Service
metadata:
  name: qwen3-coder-public
  namespace: llm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: isvc.qwen3-coder-predictor
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32092
