apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter-public
  namespace: monitoring
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: dcgm-exporter
  ports:
    - name: metrics
      port: 9400
      protocol: TCP
      targetPort: 9400
      nodePort: 32094
