apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-settings
  namespace: monitoring
data:
  retentionPeriod: "7d"
  scrapeTargets: |
    - kube-state-metrics
    - node-exporter
    - kubernetes-control-plane
    - cadvisor
    - kubelet
    - cilium
    - istio
    - argocd
    - litellm
    - kserve
    - vllm
