apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: dcgm-exporter-public
  namespace: monitoring
spec:
  jobName: dcgm-exporter-public
  targetEndpoints:
    - targets:
        - 89.108.125.7:32094
      labels:
        instance: sxmgpu
        job: dcgm-exporter-public
      path: /metrics
      scheme: http
      interval: 60s
      scrapeTimeout: 45s
