apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
patches:
  - target:
      kind: Deployment
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node-role.kubernetes.io/infra: ""
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/infra
            operator: Equal
            value: "true"
            effect: NoSchedule
