apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: llm
data:
  config.yaml: |
    model_list:
      - model_name: gpt-oss-20b
        litellm_params:
          model: openai/gpt-oss-20b
          api_base: http://89.108.125.7:32090/v1
          api_key: dummy
          include_reasoning: false
          reasoning_effort: low
          allowed_openai_params:
            - reasoning_effort
      - model_name: qwen35-9b
        litellm_params:
          model: openai/qwen35-9b
          api_base: http://89.108.125.7:32091/v1
          api_key: dummy
          chat_template_kwargs:
            enable_thinking: false
    litellm_settings:
      callbacks:
        - prometheus
