apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: llm
data:
  config.yaml: |
    model_list:
      - model_name: gpt-oss-20b
        litellm_params:
          model: openai/gpt-oss-20b
          api_base: http://gpt-oss-20b-predictor.llm.svc/v1
          api_key: dummy
      - model_name: qwen35-9b
        litellm_params:
          model: openai/qwen35-9b
          api_base: http://qwen35-9b-predictor.llm.svc/v1
          api_key: dummy
    litellm_settings:
      callbacks:
        - prometheus
