apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: llm
  labels:
    app.kubernetes.io/name: litellm
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: litellm
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 32080
