apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-istio-system.yaml
  - namespace-istio-ingress.yaml
  - ingress-nodeport-service.yaml
  - ingress-nodeport-note.yaml
