apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  deploy: |-
    {
      "defaultDeploymentMode": "Standard"
    }
  ingress: |-
    {
      "enableGatewayApi": false,
      "ingressClassName": "",
      "disableIngressCreation": true,
      "ingressDomain": "cluster.local",
      "urlScheme": "http"
    }
