apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  deploy: |-
    {
      "defaultDeploymentMode": "Standard"
    }
  ingress: |-
    {
      "enableGatewayApi": false,
      "kserveIngressGateway": "kserve/kserve-ingress-gateway",
      "ingressGateway": "kserve/kserve-ingress-gateway",
      "ingressClassName": "istio",
      "disableIngressCreation": true,
      "disableIstioVirtualHost": true,
      "ingressDomain": "cluster.local",
      "urlScheme": "http"
    }
