apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform
  source:
    repoURL: https://github.com/agud97/k8s-vllm.git
    targetRevision: main
    path: gitops/infra/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
