apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kserve
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: platform
  source:
    repoURL: https://github.com/agud97/k8s-vllm.git
    targetRevision: main
    path: gitops/platform/kserve
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
