apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  source:
    repoURL: https://openebs.github.io/dynamic-localpv-provisioner
    chart: localpv-provisioner
    targetRevision: 4.4.0
    helm:
      values: |
        analytics:
          enabled: false
        localpv:
          basePath: /var/openebs/local
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - key: node-role.kubernetes.io/infra
              operator: Equal
              value: "true"
              effect: NoSchedule
        hostpathClass:
          enabled: true
          name: openebs-hostpath
          reclaimPolicy: Delete
          isDefaultClass: false
          basePath: /var/openebs/local
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
