apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/agud97/k8s-vllm.git
    targetRevision: main
    path: gitops/argocd/self-management
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
