apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-victoriametrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  project: platform
  source:
    repoURL: https://github.com/agud97/k8s-vllm.git
    targetRevision: main
    path: gitops/platform/victoriametrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
