apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-argocd.yaml
  - app-platform-cert-manager.yaml
  - app-infra-sealed-secrets.yaml
  - app-infra-openebs.yaml
  - app-infra-istio.yaml
  - app-infra-nvidia-device-plugin.yaml
  - app-infra-dcgm-exporter.yaml
  - app-platform-knative-serving.yaml
  - app-platform-kserve.yaml
  - app-platform-victoriametrics.yaml
  - app-platform-victoriametrics-extras.yaml
  - app-app-litellm.yaml
  - app-app-openwebui.yaml
  - app-app-llm-serving.yaml
