apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-argocd.yaml
  - app-infra-sealed-secrets.yaml
  - app-infra-openebs.yaml
  - app-infra-istio.yaml
  - app-infra-nvidia-device-plugin.yaml
  - app-platform-knative-serving.yaml
  - app-platform-kserve.yaml
  - app-platform-victoriametrics.yaml
  - app-app-litellm.yaml
  - app-app-llm-serving.yaml
